# This file was generated by GoReleaser. DO NOT EDIT.
cask "eatme" do
  version "0.1.38"

  on_macos do
    on_intel do
      sha256 "e2ac32765906326b4134a2641ddfba633ee1576af6dfbe4182949e389d8e5487"
      url "https://github.com/kulapard/go-eatme/releases/download/v#{version}/go-eatme_v#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4c6de9188d9f0605f48265b05e304314c0843721249d2a4f8509c41660dec07e"
      url "https://github.com/kulapard/go-eatme/releases/download/v#{version}/go-eatme_v#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "062812c2330980bd6ff03c59925a4ae68a32a2c3f25db5bbdff6529d7a497a3a"
      url "https://github.com/kulapard/go-eatme/releases/download/v#{version}/go-eatme_v#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "34d392cf78fd68f42c01f544eab40e684314de8ae880eb1afa674022ae97119d"
      url "https://github.com/kulapard/go-eatme/releases/download/v#{version}/go-eatme_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "eatme"
  desc "Simple tool to manage multiple git/hg repositories at once. It goes through all subdirectories recursively and concurrently execute specified command in all af them."
  homepage "https://github.com/kulapard/go-eatme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eatme"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eatme"]
    end
  end

  # No zap stanza required

end
