# This file was generated by GoReleaser. DO NOT EDIT.
cask "gol" do
  version "0.1.33"

  on_macos do
    on_intel do
      sha256 "ae38c34901924c1b709292b7c3b1d0d66641448c1e2e3b1c09bd55b7f63d6f22"
      url "https://github.com/kulapard/gol/releases/download/v#{version}/gol_v#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0ed97142673827ec371e15aa7e9e6863b379c5d78ee2de2b3d4bcce08331b851"
      url "https://github.com/kulapard/gol/releases/download/v#{version}/gol_v#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9fb282ced366a87e8aebfe30b0a46661571d558d29c217e324e256989c65fb09"
      url "https://github.com/kulapard/gol/releases/download/v#{version}/gol_v#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4737c31c0f1b508322db4f4857768ffee9d31fbd1b0b4efbf19ac0fdb9f1033d"
      url "https://github.com/kulapard/gol/releases/download/v#{version}/gol_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "gol"
  desc "Terminal version of Conway's Game of Life written in Go"
  homepage "https://github.com/kulapard/gol"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gol"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gol"]
    end
  end

  # No zap stanza required

end
