# This file was generated by GoReleaser. DO NOT EDIT.
cask "gol" do
  version "0.1.32"

  on_macos do
    on_intel do
      sha256 "453ce7b2a092f5b5ae125107f4fa448ffa67624a31b56387193ba5009b9801a9"
      url "https://github.com/kulapard/gol/releases/download/v#{version}/gol_v#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b401d325a2b51e87ca4909c96007ee44a1c0fd9ab8aafc3c8e242c6e19f42db5"
      url "https://github.com/kulapard/gol/releases/download/v#{version}/gol_v#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "818f5a007117e04d23d3971933c792d8f145a416b1841c5d28841ebc9e82eb1f"
      url "https://github.com/kulapard/gol/releases/download/v#{version}/gol_v#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bff504ffa631d8c110648b229b0601b50b4bad806564b7b7e9c57a5d28ec0c52"
      url "https://github.com/kulapard/gol/releases/download/v#{version}/gol_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "gol"
  desc "Terminal version of Conway's Game of Life written in Go"
  homepage "https://github.com/kulapard/gol"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gol"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gol"]
    end
  end

  # No zap stanza required

end
