# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eatme < Formula
  desc "Simple tool to manage multiple git/hg repositories at once. It goes through all subdirectories recursively and concurrently execute specified command in all af them."
  homepage "https://github.com/kulapard/go-eatme"
  version "0.1.36"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kulapard/go-eatme/releases/download/v0.1.36/go-eatme_v0.1.36_macos_x86_64.tar.gz"
      sha256 "7d4e4e0f9ec3b9768b0cb37ed2eaca66c06558d50eb7acdeea716a31d7539d53"

      def install
        bin.install "eatme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kulapard/go-eatme/releases/download/v0.1.36/go-eatme_v0.1.36_macos_arm64.tar.gz"
      sha256 "8a963f6dbbfdb2347d47895f2188e75f644775c4e0d4666dc2933deb1183b84b"

      def install
        bin.install "eatme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kulapard/go-eatme/releases/download/v0.1.36/go-eatme_v0.1.36_linux_x86_64.tar.gz"
        sha256 "f69a793b12dc1aa2ebf4ac2f107781bfe931f949b1c98a0933700ff462f35677"

        def install
          bin.install "eatme"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kulapard/go-eatme/releases/download/v0.1.36/go-eatme_v0.1.36_linux_arm.tar.gz"
        sha256 "5eee52a4c869b8c0c3463fca104024ae48006a4c11a9001fbf21a4a0bec48b67"

        def install
          bin.install "eatme"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kulapard/go-eatme/releases/download/v0.1.36/go-eatme_v0.1.36_linux_arm64.tar.gz"
        sha256 "983a096877a3cacb02cce6e3caa94667719aeb6aa844697b94d3c0d327730aa4"

        def install
          bin.install "eatme"
        end
      end
    end
  end

  test do
    system "#{bin}/eatme branch"
  end
end
