# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eatme < Formula
  desc ""
  homepage "https://github.com/kulapard/go-eatme"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kulapard/go-eatme/releases/download/v0.1.11/go-eatme_0.1.11_Darwin_arm64.tar.gz"
      sha256 "0b94dcdf44db6ced0799b145e447fef293008ce0694012211e610281cb222522"

      def install
        bin.install "eatme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kulapard/go-eatme/releases/download/v0.1.11/go-eatme_0.1.11_Linux_arm64.tar.gz"
      sha256 "3ff7c671f5cb8d34c1d6f43ca9d4af43736275588ddde04b6c006bfc69769a6c"

      def install
        bin.install "eatme"
      end
    end
  end

  test do
    system "#{bin}/eatme branch"
  end
end
