# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gol < Formula
  desc "Terminal version of Conway's Game of Life written in Go"
  homepage "https://github.com/kulapard/gol"
  version "0.1.30"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kulapard/gol/releases/download/v0.1.30/gol_Darwin_x86_64.tar.gz"
      sha256 "af5633a9f28f766ea3bdc383afa49f353817b04c4d25991316e3c3fea350aeeb"

      def install
        bin.install "gol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kulapard/gol/releases/download/v0.1.30/gol_Darwin_arm64.tar.gz"
      sha256 "1d12dabc66195f5720e87c75a3cc17f9754208df58d2cfc5178f1fe844fea310"

      def install
        bin.install "gol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kulapard/gol/releases/download/v0.1.30/gol_Linux_x86_64.tar.gz"
        sha256 "bffb55efd5b3ee9be6abeb84e635628a2cd6e79483f3e8fe73955da19f243879"

        def install
          bin.install "gol"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/kulapard/gol/releases/download/v0.1.30/gol_Linux_armv6.tar.gz"
        sha256 "284990933b8376ac5be73af2c7a058490b05c7e64ed34b0501fd29f3bbb8b788"

        def install
          bin.install "gol"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kulapard/gol/releases/download/v0.1.30/gol_Linux_arm64.tar.gz"
        sha256 "2ab21b88a41ed4f11f2751736bec53a229bc7a9fb71cb950262bf22832bf65be"

        def install
          bin.install "gol"
        end
      end
    end
  end

  test do
    system "#{bin}/gol --version"
  end
end
