# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gol < Formula
  desc "Terminal version of Conway's Game of Life written in Go"
  homepage "https://github.com/kulapard/gol"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kulapard/gol/releases/download/v0.1.2/gol_Darwin_x86_64.tar.gz"
      sha256 "d246dc0bda515b766f080b5196fa53cf0f278e929f4756381741a47610506bbb"

      def install
        bin.install "gol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kulapard/gol/releases/download/v0.1.2/gol_Darwin_arm64.tar.gz"
      sha256 "035ebf0db58ec3b89c6a0a68c8ad597e2f4c3912f0741910a138bed8e8efca34"

      def install
        bin.install "gol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kulapard/gol/releases/download/v0.1.2/gol_Linux_arm64.tar.gz"
      sha256 "eeb4b712bd0499e544ca5a5acc69459026afce4e25857fbf553c34c90f689663"

      def install
        bin.install "gol"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kulapard/gol/releases/download/v0.1.2/gol_Linux_x86_64.tar.gz"
      sha256 "f6e742900aa9231b374b2289d39c737d26019489e3485efce652b736546bdbd7"

      def install
        bin.install "gol"
      end
    end
  end

  test do
    system "#{bin}/gol --version"
  end
end
